### ISSUE TITLE
:rocket: Roadmap for 0.1 release

### ISSUE THREAD

**Issue by daquintero** [daquintero/piel#128]
- [ ] Coverage of all new non-simulation code (since this will change in 0.2) working from the nix CI.
 - [x] Working nix release with the venv. #122 
 - [X] #127  (will take a bit more effort to properly impelement)
 - [x] #134 
 - [x]  https://github.com/gdsfactory/gdsfactory7/pull/19 means it's possible to now do a gdsfactory7 compatible release. 
 - [ ] Upgrade all code to the new version of gdsfactory7 accordingly.

**Comment by daquintero** [comment]
I'm inclined to do a few small patch releases and get a final 0.1 release that is fully stable, before completely migrating the backend simulation and experimental classes equivalence in 0.2
